const express = require('express');
const cors = require('cors');
const app = express();
const port = 3000;

// Dữ liệu sản phẩm giả (thay vì file data.ts ở frontend)
const products = [
 { id: 1, name: "ASUS ROG Strix SCAR 18 G835LW SA193W", price: 82990000, category: "gaming", image: "https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/336446/asus-rog-strix-scar-18-g835lx-ultra-9-sa193w-2-638792712349227762-750x500.jpg", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core Ultra 9"}, {label:"Số nhân", value:"16"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 5080"}, {label:"VRAM", value:"16GB GDDR7"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB DDR5"}, {label:"Ổ cứng", value:"1TB PCIe 4.0 NVMe"}]}]},
  { id: 2, name: "ASUS ROG Zephyrus G16 GU605CX QR147W", price: 119990000, category: "gaming", image: "https://cdn.tgdd.vn/Products/Images/44/322427/asus-gaming-rog-zephyrus-g16-gu605mv-ultra-9-qr135w-1-1-750x500.jpg", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core Ultra 9"}, {label:"Số nhân", value:"16"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 5090"}, {label:"VRAM", value:"24GB GDDR7"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"64GB LPDDR5X"}, {label:"Ổ cứng", value:"2TB PCIe 4.0 NVMe"}]}]},
  { id: 3, name: "HP Elitebook X360 830 G11", price: 44390000, category: "van-phong", image: "https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/331523/hp-elitebook-x360-830-g11-ultra-7-a7rc0pt-1-638661786338705759-750x500.jpg", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core Ultra 7 165U"}, {label:"Số nhân", value:"12"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"Intel Integrated Graphics"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"16GB LPDDR5"}, {label:"Ổ cứng", value:"512GB NVMe SSD"}]}]},
  { id: 4, name: "MacBook Pro 14 inch M5", price: 51790000, category: "van-phong", image: "https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/358089/macbook-pro-14-inch-m5-1-638962511548077123-750x500.jpg", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Apple M5"}, {label:"Số nhân", value:"10"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"10 nhân GPU"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"24GB Unified"}, {label:"Ổ cứng", value:"1TB SSD"}]}, {name:"Màn hình", items:[{label:"Kích thước", value:"14 inch"}, {label:"Loại", value:"Liquid Retina XDR"}]}, {name:"Cổng & kết nối", items:[{label:"Cổng", value:"MagSafe, 2x Thunderbolt 4, HDMI, Jack 3.5mm, SDXC"}, {label:"Wi-Fi/Bluetooth", value:"Wi-Fi 6E, Bluetooth 5.3"}]}, {name:"Pin & trọng lượng", items:[{label:"Pin", value:"Lên tới 18 giờ"}, {label:"Khối lượng", value:"1.6 kg"}]}]},
  { id: 5, name: "MSI Prestige 16 AI Studio B1VFG 082VN", price: 55990000, category: "design", image: "https://cdn.tgdd.vn/Products/Images/44/322958/msi-prestige-16-ai-studio-b1vfg-ultra-9-082vn-2-1-750x500.jpg", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core Ultra 9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4060"}, {label:"VRAM", value:"8GB GDDR6"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB DDR5"}, {label:"Ổ cứng", value:"1TB NVMe"}]}]},
  { id: 6, name: "Lenovo Yoga Pro 7 14IMH9 83E2006MVN", price: 41990000, category: "design", image: "https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/333196/lenovo-yoga-pro-7-14imh9-ultra-7-83e2006mvn-1-638701153555784968-750x500.jpg", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core Ultra 7"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4050"}, {label:"VRAM", value:"6GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB DDR5"}, {label:"Ổ cứng", value:"1TB NVMe"}]}]},
  { id: 7, name: "MSI Prestige 16 AI+ Mercedes AMG B2VMG", price: 49990000, category: "gaming", image: "https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/341572/msi-prestige-16-ai-mercedes-amg-b2vmg-ultra-9-288v-088vn-1-638904659240843868-750x500.jpg", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core Ultra 9 Lunar Lake"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"Intel Arc Graphics"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB DDR5"}, {label:"Ổ cứng", value:"2TB NVMe PCIe"}]}]},
  { id: 8, name: "Dell XPS 13 9350 - PP9H1", price: 64990000, category: "van-phong", image: "https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/342757/dell-xps-13-9350-ultra-7-258v-pp9h1-2-638917189604832011-750x500.jpg", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core Ultra 7"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"Intel Arc Graphics"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB LPDDR5X"}, {label:"Ổ cứng", value:"1TB NVMe"}]}]},
  { id: 9, name: "Acer Swift X14 SFX14 72G 79UW", price: 48990000, category: "design", image: "https://product.hstatic.net/200000722513/product/ava_8884341ac5f14efb8e3a4710682698a2_master.png", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core Ultra 7"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4070"}, {label:"VRAM", value:"8GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB LPDDR5"}, {label:"Ổ cứng", value:"1TB NVMe"}]}]},
  
  { id: 10, name: "MacBook Pro 14″ M5 (16GB / 512GB)", price: 52990000, category: "van-phong", image: 	"https://bizweb.dktcdn.net/thumb/1024x1024/100/116/…ducts/macbook-pro-14-inch-chip-m5-space-black.png", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Apple M5"}, {label:"Số nhân", value:"10"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"10 nhân GPU"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"16GB Unified"}, {label:"Ổ cứng", value:"512GB SSD"}]}, {name:"Màn hình", items:[{label:"Kích thước", value:"14 inch"}, {label:"Loại", value:"Liquid Retina XDR"}]}]},
  
  { id: 11, name: "MacBook Pro 14″ M5 (24GB / 1TB)", price: 61990000, category: "van-phong", image: "https://store.storeimages.cdn-apple.com/1/as-image…JNaHI5aXZSOWk3dEhoQkx6STlJSlZ4M0pKaFh6c2piamliR2k", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Apple M5"}, {label:"Số nhân", value:"10"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"10 nhân GPU"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"24GB Unified"}, {label:"Ổ cứng", value:"1TB SSD"}]}, {name:"Màn hình", items:[{label:"Kích thước", value:"14 inch"}, {label:"Loại", value:"Liquid Retina XDR"}]}]},
  
  { id: 12, name: "MacBook Pro 14″ M4 Pro (24GB / 512GB)", price: 47890000, category: "van-phong", image: "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:…/media/catalog/product/t/e/text_ng_n_1__6_138.png", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Apple M4 Pro"}, {label:"Số nhân", value:"10"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"10 nhân GPU"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"24GB Unified"}, {label:"Ổ cứng", value:"512GB SSD"}]}, {name:"Màn hình", items:[{label:"Kích thước", value:"14 inch"}, {label:"Loại", value:"Liquid Retina XDR"}]}]},
  
  { id: 13, name: "MacBook Pro 14″ M4 Pro (36GB / 1TB)", price: 63990000, category: "van-phong", image: "	https://bachlongstore.vn/vnt_upload/product/10_2024/423.png", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Apple M4 Pro"}, {label:"Số nhân", value:"10"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"10 nhân GPU"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"36GB Unified"}, {label:"Ổ cứng", value:"1TB SSD"}]}, {name:"Màn hình", items:[{label:"Kích thước", value:"14 inch"}, {label:"Loại", value:"Liquid Retina XDR"}]}]},
  
  { id: 14, name: "MacBook Pro 14″ M4 Max (48GB / 2TB)", price: 89990000, category: "van-phong", image: "https://product.hstatic.net/200000348419/product/c…aster_174fbe4b53e2481c917f95f66e728f96_grande.png", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Apple M4 Max"}, {label:"Số nhân", value:"12"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"12 nhân GPU"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"48GB Unified"}, {label:"Ổ cứng", value:"2TB SSD"}]}, {name:"Màn hình", items:[{label:"Kích thước", value:"14 inch"}, {label:"Loại", value:"Liquid Retina XDR"}]}]},
  
  { id: 15, name: "MacBook Air 15″ M4 (24GB / 1TB)", price: 43990000, category: "van-phong", image: "	https://bizweb.dktcdn.net/100/176/601/products/app…1-34c8-40ba-bf2f-a9775cbda867.png?v=1744679388193", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Apple M4"}, {label:"Số nhân", value:"8"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"8 nhân GPU"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"24GB Unified"}, {label:"Ổ cứng", value:"1TB SSD"}]}, {name:"Màn hình", items:[{label:"Kích thước", value:"15 inch"}, {label:"Loại", value:"Liquid Retina"}]}]},
  
  { id: 16, name: "Razer Blade 16 (2025) RTX 4090", price: 119900000, category: "gaming", image: "hhttps://lapvip.vn/upload/products/original/razer-blade-16-2025-1743059447.png", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core i9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4090"}, {label:"VRAM", value:"16GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB DDR5"}, {label:"Ổ cứng", value:"1TB NVMe"}]}]},
  
  { id: 17, name: "Razer Blade 14 (Ryzen 9 / 32GB / 1TB)", price: 84990000, category: "gaming", image: "https://m.media-amazon.com/images/I/81PB7KPoaEL._AC_UF894,1000_QL80_.jpg", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"AMD Ryzen 9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4070"}, {label:"VRAM", value:"8GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB DDR5"}, {label:"Ổ cứng", value:"1TB NVMe"}]}]},
  
  { id: 18, name: "Asus ROG Zephyrus Duo 16 GX650", price: 139900000, category: "gaming", image: "https://cdn2.cellphones.com.vn/x/media/catalog/product/l/a/laptop-asus-gaming-rog-zephyrus-duo-16-gx650pz-nm031w-1.png", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core i9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4090"}, {label:"VRAM", value:"16GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"64GB DDR5"}, {label:"Ổ cứng", value:"2TB NVMe"}]}]},
  
  { id: 19, name: "Acer Predator Triton 18 PT-18 RTX 4080", price: 109900000, category: "gaming", image: "https://bizweb.dktcdn.net/thumb/grande/100/512/769/products/acer-helios-18-2024-2.jpg?v=1735451185897", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core i9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4080"}, {label:"VRAM", value:"16GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB DDR5"}, {label:"Ổ cứng", value:"2TB NVMe"}]}]},
  
  { id: 20, name: "Lenovo Legion 9i (16″ / i9 / RTX 4090)", price: 124900000, category: "gaming", image: "https://product.hstatic.net/200000722513/product/83ag0047vn_b57e907d045e448b9845f3754b097d5d_master.png", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core i9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4090"}, {label:"VRAM", value:"16GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB DDR5"}, {label:"Ổ cứng", value:"2TB NVMe"}]}]},
  
  { id: 21, name: "HP Spectre x360 16 (OLED / i7 / 32GB)", price: 79990000, category: "van-phong", image: "https://www.laptopvip.vn/images/detailed/24/hp-spectre-x360-2-in-1-nightfall-black-3-adot-2u-www.laptopvip.vn-1623991310.jpg", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core i7"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"Intel Iris Xe"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB LPDDR5"}, {label:"Ổ cứng", value:"1TB NVMe"}]}]},
  
  { id: 22, name: "Asus Zenbook Pro 14 Duo OLED (i9 / 64GB)", price: 89990000, category: "thiet-ke", image: "https://cdn2.cellphones.com.vn/x/media/catalog/product/2/_/2_304.png", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core i9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4070"}, {label:"VRAM", value:"12GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"64GB DDR5"}, {label:"Ổ cứng", value:"2TB NVMe"}]}]},
  
  { id: 23, name: "Lenovo ThinkPad X1 Carbon Gen 12 (i7 / 32GB)", price: 68990000, category: "van-phong", image: "https://p3-ofp.static.pub//fes/cms/2023/06/06/gp49wjme8nzqm6tghn7qggut4pwlyj864801.png?width=400&height=400", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core i7"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"Intel Iris Xe"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB LPDDR5"}, {label:"Ổ cứng", value:"1TB NVMe"}]}]},
  
  { id: 24, name: "Lenovo ThinkPad P1 Gen 6 (i9 / RTX A3000)", price: 124900000, category: "thiet-ke", image: "https://p3-ofp.static.pub//fes/cms/2023/06/06/gp49wjme8nzqm6tghn7qggut4pwlyj864801.png?width=400&height=400", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core i9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX A3000"}, {label:"VRAM", value:"12GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"64GB DDR5"}, {label:"Ổ cứng", value:"2TB NVMe"}]}]},
  
  { id: 25, name: "Acer ConceptD 7 Ezel (i7 / RTX 3070)", price: 97990000, category: "thiet-ke", image: "https://product.hstatic.net/200000722513/product/1_59d2bbef2fdb416084ad2fd4c408459e_80bf0f39b0554edeab5c8aa2a90793a3_master.png", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core i7"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 3070"}, {label:"VRAM", value:"8GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB DDR4"}, {label:"Ổ cứng", value:"1TB NVMe"}]}]},
  
  { id: 26, name: "Gigabyte Aero 16 OLED (i9 / RTX 4080)", price: 134900000, category: "thiet-ke", image: "https://d28jzcg6y4v9j1.cloudfront.net/media/social/articles/2023/5/4/gigabyte-aero-16-oled-thinkpro-thumb-thinkpro.png", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core i9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4080"}, {label:"VRAM", value:"16GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"64GB DDR5"}, {label:"Ổ cứng", value:"2TB NVMe"}]}]},
  
  { id: 27, name: "Asus ProArt Studiobook 16 OLED (Ryzen 9 / RTX 4070)", price: 124900000, category: "thiet-ke", image: "https://hungphatlaptop.com/wp-content/uploads/2023/08/Asus-ProArt-Studiobook-16-OLED-H7604JV-DS96-2023-H1.jpeg", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"AMD Ryzen 9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4070"}, {label:"VRAM", value:"12GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"64GB DDR5"}, {label:"Ổ cứng", value:"2TB NVMe"}]}]},
  
  { id: 28, name: "HP Omen 16 (Ryzen 9 / RTX 4080)", price: 109900000, category: "gaming", image: "https://lh3.googleusercontent.com/lRn9L3mjlF0bycbj-MLtG9aX9-AJXLSXlK2Jka5-k9Kg9tVCnoMRfNyO2HZNbDgK8As4pKl08K8J8ECYbv8mGg-z7KRVTqoR=w500-rw", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"AMD Ryzen 9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4080"}, {label:"VRAM", value:"16GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"32GB DDR5"}, {label:"Ổ cứng", value:"2TB NVMe"}]}]},
  
  { id: 29, name: "MSI GT77 Titan (i9 / RTX 4090)", price: 189900000, category: "gaming", image: "https://bizweb.dktcdn.net/100/386/607/products/msi-titan-18-hx-cong-ket-noi-trai-7dbb8ef5-63c6-4805-bdf9-38ce10c65daf.jpg?v=1736256727167", techSpecs: [{name:"Bộ xử lý", items:[{label:"CPU", value:"Intel Core i9"}]}, {name:"Đồ hoạ (GPU)", items:[{label:"GPU", value:"NVIDIA RTX 4090"}, {label:"VRAM", value:"24GB"}]}, {name:"Bộ nhớ RAM, Ổ cứng", items:[{label:"RAM", value:"64GB DDR5"}, {label:"Ổ cứng", value:"4TB NVMe"}]}]}
];

app.use(cors()); // Cho phép request từ Angular (chạy ở port khác)

// API endpoint để lấy tất cả sản phẩm
app.get('/api/products', (req, res) => {
  res.json(products);
});

// API endpoint để lấy một sản phẩm theo ID
app.get('/api/products/:id', (req, res) => {
  const id = parseInt(req.params.id);
  const product = products.find(p => p.id === id);
  if (product) {
    res.json(product);
  } else {
    res.status(404).send('Product not found');
  }
});

app.listen(port, () => {
  console.log(`Express server listening at http://localhost:${port}`);
});
